# Generated by Django 4.0.6 on 2022-08-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='users',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='userss',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.profile'),
        ),
    ]
